"""remove auth profiles and user scoping

Revision ID: 510ae7725634
Revises: 6a085e25b4d5
Create Date: 2026-08-19 05:23:23.738855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '510ae7725634'
down_revision: Union[str, Sequence[str], None] = '6a085e25b4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'user_id')
    op.drop_constraint(op.f('saved_searches_user_id_fkey'), 'saved_searches', type_='foreignkey')
    op.drop_column('saved_searches', 'user_id')
    op.drop_constraint(op.f('search_jobs_user_id_fkey'), 'search_jobs', type_='foreignkey')
    op.drop_column('search_jobs', 'user_id')
    op.drop_constraint(op.f('settings_user_id_key_key'), 'settings', type_='unique')
    op.create_unique_constraint(None, 'settings', ['key'])
    op.drop_constraint(op.f('settings_user_id_fkey'), 'settings', type_='foreignkey')
    op.drop_column('settings', 'user_id')
    op.drop_table('profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('settings_user_id_fkey'), 'settings', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'settings', type_='unique')
    op.create_unique_constraint(op.f('settings_user_id_key_key'), 'settings', ['user_id', 'key'], postgresql_nulls_not_distinct=False)
    op.add_column('search_jobs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('search_jobs_user_id_fkey'), 'search_jobs', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('saved_searches', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('saved_searches_user_id_fkey'), 'saved_searches', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'profiles', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey')),
    sa.UniqueConstraint('email', name=op.f('profiles_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
